// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDFH5QVTeOMUYOAvUJJmGKJpiVY_bU_Pw',
    appId: '1:836098194394:web:38baee90b9160c36581ee3',
    messagingSenderId: '836098194394',
    projectId: 'scoutify-iot',
    authDomain: 'scoutify-iot.firebaseapp.com',
    databaseURL: 'https://scoutify-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scoutify-iot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlHt2E6aaTFxda9JuQnYqqhEZqUGBlMYg',
    appId: '1:836098194394:android:62093a66c0e56a69581ee3',
    messagingSenderId: '836098194394',
    projectId: 'scoutify-iot',
    databaseURL: 'https://scoutify-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scoutify-iot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEgJUBgGUkgFv39v4457d0Bh9SWU_w8Ec',
    appId: '1:836098194394:ios:aa0f75027d97fc0b581ee3',
    messagingSenderId: '836098194394',
    projectId: 'scoutify-iot',
    databaseURL: 'https://scoutify-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scoutify-iot.appspot.com',
    iosClientId: '836098194394-fse41ksqv4duvau0rt208t138p2bkhrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGoogleMapTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEgJUBgGUkgFv39v4457d0Bh9SWU_w8Ec',
    appId: '1:836098194394:ios:aa0f75027d97fc0b581ee3',
    messagingSenderId: '836098194394',
    projectId: 'scoutify-iot',
    databaseURL: 'https://scoutify-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scoutify-iot.appspot.com',
    iosClientId: '836098194394-fse41ksqv4duvau0rt208t138p2bkhrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGoogleMapTesting',
  );
}
